owl_agent/owl_agent/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns ,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owl_agent/website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('register/', views.role_choose, name='register'),
    path('register_job_seeker/', views.register_Job_Seeker, name='register_job_seeker'),
    path('register_company/', views.register_Company, name='register_company'),
    path('sent/', views.activation_sent_view, name="sent"),
    path('about/', views.about_view, name='about'),
    path('contact/', views.contact_view, name='contact'),
    path('job-details/<int:pk>', views.job_details_view, name='job-details'),
    path('job-listing/', views.job_listing_view, name='job-listing'),
    path('job-listing/filter', views.job_filter_view, name='job-filter'),

    # EKLENDİ
    path('apply_job/<int:pk>', views.apply_job_view, name='apply_job'),

    path('blog/', views.blog_view, name='blog'),
    path('blog/single/', views.single_blog_view, name='single-blog'),
    path('elements/', views.elements_view, name='elements'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/approve/<int:pk>', views.approve_companies, name='company_approve'),
    path('dashboard/reject/<int:pk>', views.reject_companies, name='company_reject'),

    path('dashboard/delete/<int:pk>', views.delete_job_offer, name='job-delete'),
    # path('edit_profile_job_seeker/', views.edit_profile_job_seeker, name='edit_profile_job_seeker'),
    # path('my_profile/', views.my_profile, name='my_profile'),
    path('add_cv/<int:pk>', views.add_cv, name='add_cv'),
    path('delete/<int:pk>', views.delete_cv, name='delete_cv'),
    path('add_cv', views.add_cv, name='add_cv'),

    path('company_profile/<int:pk>', views.company_profile, name='company_profile'),
    path('company_profile/deleteJobOffer/<int:pk>', views.company_delete_job_offer, name='company_delete_job_offer'),

    path('job_seeker_profile/<int:pk>', views.job_seeker_profile, name='job_seeker_profile'),
    path('edit_profile_company/<int:pk>', views.edit_profile_company, name='edit_profile_company'),
    path('edit_profile_job_seeker/<int:pk>', views.edit_profile_job_seeker, name='edit_profile_job_seeker'),
    path('job/post/', views.post_job, name='post_job'),
    path('job/post/sent', views.job_sent_view, name='job_sent'),
    path('dashboardList/', views.admin_dashboard_list, name='admin_dashboard_list'),
    path('dashboardList/deleteCompany/<int:pk>', views.admin_delete_companies, name='admin_delete_companies'),
    path('dashboardList/deleteJobSeeker/<int:pk>', views.admin_delete_jobseeker, name='admin_delete_jobseeker'),
    path('job_applicants/<int:pk>', views.job_applicant_view, name='job_applicants'),

]

owl_agent/website/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class User_Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Company_Profile(User_Profile):
    image = models.ImageField(upload_to='company_image', null=True, blank=True, default='company_image/default.png')
    company_name = models.CharField(max_length=100)
    tax_id = models.IntegerField()
    website = models.CharField(max_length=100)
    foundation_year = models.IntegerField()

    def get_profile_url(self):
        return "/company_profile/{}".format(self.user.pk)


class Job_Seeker_Profile(User_Profile):
    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    gender = models.CharField(max_length=1, choices=GENDER, null=True, blank=True)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    birth_date = models.DateField()
    carrier_list = models.CharField(max_length=2000)
    portfolio_link = models.CharField(max_length=100)
    image = models.ImageField(upload_to='job_seeker_image', null=True, blank=True,
                              default='job_seeker_image/default.png')

    def get_profile_url(self):
        return "/job_seeker_profile/{}".format(self.user.pk)



class CV(models.Model):
    name = models.CharField(max_length=20)
    cv_img = models.ImageField(upload_to='cv_image', null=True, blank=True, default='cv_img/default')
    almater = models.CharField(max_length=100)
    address = models.TextField(max_length=500)
    graduation_date = models.DateField()
    internships = models.TextField(max_length=2000)
    gpa = models.DecimalField(max_digits=20, decimal_places=2)
    experience_field = models.TextField(max_length=500)
    extras = models.TextField(max_length=1000)
    interests = models.TextField(max_length=1000)
    owner = models.ForeignKey(Job_Seeker_Profile, on_delete=models.CASCADE, related_name='%(class)s_owner')

    MILITARY_STATUS_CHOICES = [
        (1, 'Done'),
        (0, 'Not Done'),
    ]
    military_status = models.IntegerField(
        choices=MILITARY_STATUS_CHOICES,
        default=1,
    )

    LICENCES_STATUS_CHOICES = [
        (1, 'Have'),
        (0, 'Have Not'),
    ]
    licences_status = models.IntegerField(
        choices=LICENCES_STATUS_CHOICES,
        default=1,
    )

    def __str__(self):
        return self.name


class Job_Offer(models.Model):
    CATEGORIES = (
        ('design', 'Design & Creative'),
        ('design_development', 'Design & Development'),
        ('sales_marketing', "Sales & Marketing"),
        ('mobile_app', "Mobile Application"),
        ('construction', "Construction"),
        ("it", "Information Technology"),
        ("real_estate", "Real Estate"),
        ("content_writer", "Content Writer")
    )

    TYPE = (
        ("full_time", "Full Time"),
        ("part_time", "Part Time"),
        ("intern", "Internship"),
        ("remote", "Remote")
    )

    EXPERIENCE = (
        ("0_years", "No experience"),
        ("1_2_years", "1-2 years"),
        ("2_3_years", "2-3 years"),
        ("3_6_years", "3-6 years"),
        ("6_more_years", "6-more years")
    )

    LOCATION = (
        ("istanbul", "Istanbul"),
        ("ankara", "Ankara"),
        ("izmir", "Izmir"),
        ("bursa", "Bursa")
    )

    categories = models.CharField(max_length=25, choices=CATEGORIES)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=10000)
    required_skills = models.CharField(max_length=10000, blank=True)
    education = models.CharField(max_length=10000, blank=True)
    start_date = models.DateField(blank=True)
    post_date = models.DateField(auto_now_add=True, blank=True)
    type = models.CharField(max_length=25, blank=True, choices=TYPE)
    location = models.CharField(max_length=500, choices=LOCATION)
    work_level = models.CharField(max_length=100, blank=True)
    experience = models.CharField(max_length=100, blank=True, choices=EXPERIENCE)
    salary = models.CharField(max_length=100, blank=True)
    company = models.ForeignKey(Company_Profile, on_delete=models.CASCADE, related_name='%(class)s_company')

    def get_applicants_url(self):
        return "/job_applicants/{}/".format(self.pk)

    def delete_job_offer_url(self):
        return "/company_profile/job_offer/delete/{}".format(self.pk)


class Application(models.Model):
    applicant = models.ForeignKey(Job_Seeker_Profile, on_delete=models.CASCADE, related_name='%(class)s_applicant',
                                  default="")
    employer = models.ForeignKey(Company_Profile, on_delete=models.CASCADE, related_name='%(class)s_employer',
                                 default="")
    job_offer = models.ForeignKey(Job_Offer, on_delete=models.CASCADE, related_name='%(class)s_job_offer',
                                  default="")
    cv = models.ForeignKey(CV, on_delete=models.CASCADE, related_name='%(class)s_cv', default="", blank=True, null=True)
    file = models.FileField(null=True, blank=True, upload_to="applications/")

## Django have some notification system , we can add Notification Model when we get there.

owl_agent/website/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from .models import Company_Profile, Job_Seeker_Profile, CV, Application

User = get_user_model()

USER_TYPES = (
    ('job_seeker', 'Job_Seeker'),
    ('company', 'Company'),
)


class RoleChooseForm(forms.Form):
    type = forms.ChoiceField(choices=USER_TYPES)


class Job_Seeker_RegisterForm(UserCreationForm):
    name = forms.CharField(max_length=100, help_text='Name', widget=forms.TextInput)
    surname = forms.CharField(max_length=100, help_text='Surname', widget=forms.TextInput)
    birth_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    carrier_list = forms.CharField(max_length=2000, help_text='Carrier List', widget=forms.TextInput)
    portfolio_link = forms.CharField(max_length=100, help_text='Portfolio Link', widget=forms.TextInput)

    class Meta:
        model = User
        fields = ('username', 'name', 'surname', 'password1', 'password2')


class Company_RegisterForm(UserCreationForm):
    company_name = forms.CharField(max_length=100, help_text='Company Name', widget=forms.TextInput)
    tax_id = forms.IntegerField()
    website = forms.CharField(max_length=100, help_text='Website', widget=forms.TextInput)
    foundation_year = forms.IntegerField()

    class Meta:
        model = User
        fields = ('username', 'company_name', 'password1', 'password2')


class EditCompanyProfileForm(forms.Form):
    company_name = forms.CharField(max_length=100, widget=forms.TextInput)
    foundation_year = forms.IntegerField()
    tax_id = forms.IntegerField()
    website = forms.CharField(max_length=100, widget=forms.TextInput)
    email = forms.EmailField(max_length=150, widget=forms.EmailInput)

    class Meta:
        model = Company_Profile
        fields = ('company_name', 'email', 'foundation_year', 'tax_id', 'website')


class CVForm(forms.ModelForm):
    class Meta:
        model = CV
        fields = [
            'name',
            'cv_img',
            'address',
            'military_status',
            'licences_status',
            'almater',
            'graduation_date',
            'internships',
            'gpa',
            'experience_field',
            'extras',
            'interests'
        ]
        widgets = {
            'graduation_date': forms.DateInput(attrs={'class': 'form-control',
                                                      'type': 'date'}),
        }


class JobApplyForm(forms.ModelForm):
    def __init__(self, *args, job_seeker, **kwargs):
        super(JobApplyForm, self).__init__(*args, **kwargs)
        self.fields['cv'].queryset = CV.objects.filter(owner=job_seeker)

    class Meta:
        model = Application
        fields = 'cv', 'file'
        labels = {
            "file": "CV (pdf format)"
        }

owl_agent/templates/website/List.html
{% extends 'website/base.html' %}
{% block title %}
Owls Agent Admin Dashboard
{% endblock %}

{% load static %}
{% block content %}
<center>
    <br><br>
<button type="button" class="collapsible">List Of Companies</button>
<div class="content">
 <table>
    <tr>
    <th>Company Name</th>
    <th>Tax Id</th>
    <th>Website</th>
    <th>Foundation Year</th>

  </tr>
        {% for x in querySet %}

            <tr>
                <td>{{ x.company_name }}</td>
                <td>{{ x.tax_id }}</td>
                <td>{{ x.website }}</td>
                <td>{{ x.foundation_year }}</td>


                <td class="text-center">
                    <a href="/dashboardList/deleteCompany/{{ x.id }}">
                        <button type="button" class="btn btn-success">Delete</button>
                                    </a>
            </tr>


        {% endfor %}

</table>

</div></center>
<br>
<br>
<center>
    <br><br>
<button type="button" class="collapsible">List Of Job Seekers</button>
<div class="content">
 <table>
    <tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Birth_Date</th>
    <th>Carrier List </th>
        <th>Portfolio Link </th>
  </tr>
        {% for y in listing_jobseeker %}

            <tr>
                <td>{{ y.name }}</td>
                <td>{{ y.surname }}</td>
                <td>{{ y.birth_date }}</td>
                <td>{{ y.carrier_list }}</td>
                <td>{{ y.portfolio_link }}</td>




                     <td class="text-center">
                    <a href="/dashboardList/deleteJobSeeker/{{ y.id }}">
                        <button type="button" class="btn btn-success">Delete</button>
                                    </a>
            </tr>
        {% endfor %}
</table>

</div></center> <br><br>

<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>

{% endblock %}

owl_agent/templates/website/activation_sent.html
{% extends 'website/base.html' %}
{% block title %}
You are welcome!
{% endblock %}
{% block content %}


<div class="container h-50">
    <div class="d-flex justify-content-center h-100">
        <div class="col-md-6 text-center">
            <div class="card mb-4">
                <div class="card-header">
                    Congratulations!
                </div>
                <div class="card-body">

                        <div class="input-group mb-3">
                               {% if user_type == 'job_seeker' %}
                             <h3>Your account created successfully!</h3>
                        {% else %}
                        <h3>Your account created successfully! Wait for the admin to prove your account.</h3>
                    {% endif %}


            </div>

        </div>
    </div>
</div>
</div>
</div>


{% endblock %}

owl_agent/templates/website/admin_job_listing.html
{% extends 'website/base.html' %}
{% block title %}
    Owls Agent Admin Dashboard
{% endblock %}

{% load static %}
{% block content %}
<div class="container h-50">

</div>

{% endblock %}

owl_agent/templates/website/apply_job.html
{% extends 'website/base.html' %}
{% block title %}
Owls Agent Job Details Page
{% endblock %}
{% load static %}
{% block content %}

{% load crispy_forms_tags %}
<main>

    <!-- Hero Area End -->
    <div class="job-post-company pt-120 pb-120">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <center><h1 class="lead" style="font-weight: bold">APPLY FOR A JOB </h1></center>

                    <hr>
                    <form action="" method="POST" class="" enctype="multipart/form-data">
                        {% if messages|length < 1  %}
                        {% csrf_token %}
                        {{ form | crispy }}

                        <div class="row form-group" style="margin-left:27%">
                            <div class="col-md-12 ml-1">
                                <input type="submit" value="Confirm Application"
                                       class="btn btn-primary btn-md text-white">
                            </div>
                        </div>
                        {% endif %}
                    </form>
                </div>
            </div>
            {% for message in messages %}
            <p id="messages" align="center">{{message}}</p>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

owl_agent/templates/website/job_listing.html
{% extends 'website/base.html' %}
{% block title %}
Owls Agent Job Listing Page
{% endblock %}
{% load static %}
{% block content %}
<main>

    <!-- Hero Area Start-->
    <div class="slider-area ">
        <div class="single-slider section-overly slider-height2 d-flex align-items-center"
             data-background="{% static 'img/hero/about.jpg'%}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Get your job</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero Area End -->
    <!-- Job List Area Start -->
    <div class="job-listing-area pt-120 pb-120">
        <div class="container">
            <div class="row">
                <!-- Left content -->
                <div class="col-xl-3 col-lg-3 col-md-4">
                    <div class="row">
                        <div class="col-12">
                            <div class="small-section-tittle2 mb-45">
                                <div class="ion">
                                    <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            xmlns:xlink="http://www.w3.org/1999/xlink"
                                            width="20px" height="12px">
                                        <path fill-rule="evenodd" fill="rgb(27, 207, 107)"
                                              d="M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z"/>
                                    </svg>
                                </div>
                                <h4>Filter Jobs</h4>
                            </div>
                        </div>
                    </div>

                    <form action="{% url 'job-filter' %}" method="POST">
                        {% csrf_token %}
                        <!-- Job Category Listing start -->
                        <div class="job-category-listing mb-50">
                            <!-- single one -->
                            <div class="single-listing">
                                <div class="small-section-tittle2">
                                    <h4>Job Category</h4>
                                </div>
                                <!-- Select job items start -->
                                <div class="select-job-items2">
                                    <select id="categories" name="categories">
                                        <option value="all">All</option>
                                        <option value="design">Design & Creative</option>
                                        <option value="design_development">Design & Development</option>
                                        <option value="sales_marketing">Sales & Marketing</option>
                                        <option value="mobile_app">Mobile Application</option>
                                        <option value="construction">Construction</option>
                                        <option value="it">Information Technology</option>
                                        <option value="real_estate">Real Estate</option>
                                        <option value="content_writer">Content Writer</option>
                                    </select>
                                </div>
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-80 pb-30">
                                    <div class="small-section-tittle2">
                                        <h4>Job Type</h4>
                                    </div>
                                    <label class="container">Full Time
                                        <input type="checkbox" name="type []" value="full_time" class="save-cb-state" id="option1">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Part Time
                                        <input type="checkbox" name="type []" value="part_time" class="save-cb-state" id="option2">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Remote
                                        <input type="checkbox" name="type []" value="remote" class="save-cb-state" id="option3">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">Intern
                                        <input type="checkbox" name="type []" value="intern" class="save-cb-state" id="option4">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single two -->
                            <div class="single-listing">
                                <!--  Select job items End-->
                                <!-- select-Categories start -->
                                <div class="select-Categories pt-10 pb-40">
                                    <div class="small-section-tittle2">
                                        <h4>Experience</h4>
                                    </div>
                                    <label class="container">No experience
                                        <input type="checkbox" name="experience []" value="0_years" class="save-cb-state" id="option5">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">1-2 Years
                                        <input type="checkbox" name="experience []" value="1_2_years" class="save-cb-state" id="option6">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">2-3 Years
                                        <input type="checkbox" name="experience []" value="2_3_years" class="save-cb-state" id="option7">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">3-6 Years
                                        <input type="checkbox" name="experience []" value="3_6_years" class="save-cb-state" id="option8">
                                        <span class="checkmark"></span>
                                    </label>
                                    <label class="container">6-more..
                                        <input type="checkbox" name="experience []" value="6_more_years" class="save-cb-state" id="option9">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                            <!-- single three -->
                            <div class="single-listing">
                                <!-- select-Categories start -->
                                <div class="select-Categories">
                                    <button type="submit" class="genric-btn info radius">Filter</button>
                                </div>
                                <!-- select-Categories End -->
                            </div>
                        </div>
                        <!-- Job Category Listing End -->
                    </form>
                </div>
                <!-- Right content -->
                <div class="col-xl-9 col-lg-9 col-md-8">
                    <!-- Featured_job_start -->
                    <section class="featured-job-area">
                        <div class="container">
                            <!-- Count of Job list Start -->
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="count-job mb-35">
                                        <span>{{ job_offer_count }} Jobs found</span>
                                    </div>
                                </div>
                            </div>
                            <!-- Count of Job list End -->
                            <!-- single-job-content -->
                            {% for job in job_offer %}
                            <div class="single-job-items mb-30">

                                <div class="job-items">
                                    <div class="company-img">
                                        <a href="#"><img src="{{ job.company.image.url }}" alt="company_image"
                                                         width="85" height="85"></a>
                                    </div>
                                    <div class="job-tittle job-tittle2">
                                        <a href="#">
                                            <h4><a href="{% url 'job-details' pk=job.id  %}">{{ job.title }}</a> </h4>
                                        </a>
                                        <ul>
                                            <li>{{ job.company.company_name }}</li>
                                            <li><i class="fas fa-map-marker-alt"></i>{{ job.get_location_display }}</li>
<!--                                            <li>{{job.salary}}</li>-->
                                            <li>{{ job.get_type_display }}</li>
                                            <li>{{ job.get_experience_display }}</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="items-link items-link2 f-right">
                                    <a href="{% url 'job-details' pk=job.id  %}">View Detail</a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </section>
                    <!-- Featured_job_end -->
                </div>
            </div>
        </div>
    </div>
    <!-- Job List Area End -->
    <!--Pagination Start  -->
<!--    <div class="pagination-area pb-115 text-center">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-xl-12">-->
<!--                    <div class="single-wrap d-flex justify-content-center">-->
<!--                        <nav aria-label="Page navigation example">-->
<!--                            <ul class="pagination justify-content-start">-->
<!--                                {% if job_offer.has_previous %}-->
<!--                                <li class="page-item"><a class="page-link" href="{{ job_offer.previous_page_number }}">Previous</a>-->
<!--                                </li>-->
<!--                                {% endif %}-->
<!--                                {% if job_offer.has_next %}-->
<!--                                <li class="page-item"><a class="page-link"-->
<!--                                                         href="{{ job_offer.next_page_number }}">Next</a></li>-->
<!--                                {% endif %}-->

<!--                            </ul>-->
<!--                        </nav>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <!--Pagination End  -->
<script>
// Avoid scoping issues by encapsulating code inside anonymous function
(function() {
  // variable to store our current state
  var cbstate;

  // bind to the onload event
  window.addEventListener('load', function() {
    // Get the current state from localstorage
    // State is stored as a JSON string
    cbstate = JSON.parse(localStorage['CBState'] || '{}');

    // Loop through state array and restore checked
    // state for matching elements
    for(var i in cbstate) {
      var el = document.querySelector('input[id="' + i + '"]');
      if (el) el.checked = true;
    }

    // Get all checkboxes that you want to monitor state for
    var cb = document.getElementsByClassName('save-cb-state');

    // Loop through results and ...
    for(var i = 0; i < cb.length; i++) {

      //bind click event handler
      cb[i].addEventListener('click', function(evt) {
        // If checkboxe is checked then save to state
        if (this.checked) {
          cbstate[this.id] = true;
        }

    // Else remove from state
        else if (cbstate[this.id]) {
          delete cbstate[this.id];
        }

    // Persist state
        localStorage.CBState = JSON.stringify(cbstate);
      });
    }
  });
})();
</script>

</main>
{% endblock %}

owl_agent/templates/website/job_sent.html
{% extends 'website/base.html' %}
{% block title %}
Your job posting listing!
{% endblock %}
{% block content %}


<div class="container h-50">
    <div class="d-flex justify-content-center h-100">
        <div class="col-md-6 text-center">
            <div class="card mb-4">
                <div class="card-header">
                    Congratulations!
                </div>
                <div class="card-body">

                        <div class="input-group mb-3">

                        <h3>Your job posting created successfully!</h3>



            </div>

        </div>
    </div>
</div>
</div>
</div>


{% endblock %}